# Generated by Django 2.1.2 on 2019-06-06 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HouseSearch', '0010_auto_20181127_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TextField(max_length=60)),
                ('end', models.TextField(max_length=60)),
                ('people', models.PositiveIntegerField(default=1)),
                ('house', models.ForeignKey(on_delete='Cascade', to='HouseSearch.House')),
                ('user', models.ForeignKey(on_delete='Cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
