# Generated by Django 2.1.2 on 2019-06-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('HouseSearch', '0012_auto_20190608_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.TextField(max_length=60)),
                ('href', models.TextField(max_length=400)),
                ('photo', models.ImageField(blank=True, upload_to='advertising/photo/')),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField()),
                ('title', models.ForeignKey(on_delete='Cascade', to='HouseSearch.House')),
            ],
        ),
    ]
