# Generated by Django 2.1.2 on 2019-06-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserProfile', '0022_auto_20181125_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='virifield',
            field=models.CharField(
                choices=[('VR', 'Сhecked'), ('WT', 'Wait for check'), ('RJ', 'Denied'), ('UF', 'Undefined')],
                default='UF', max_length=2),
        ),
    ]
